### PR TITLE
Update Power Subsystem

### PR DESCRIPTION
**Pull request by Hawk652**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
Currents don't necessarily sum unless they are all leaving the same node. You need to consider the voltage at which the currents occur. 

The ripple voltage analysis is not sufficient because you have not considered what the constraints on the limit voltage are. Based on what do you say 50 mV is acceptable?

Also, please be sure to request review from me when you update this.

**Review by JesseTNRoberts — COMMENTED** [review]
It looks like you have not considered the effect of the motors being switched when looking at the ripple.

**Review by JesseTNRoberts — COMMENTED** [review]
It sounds like the design may need a way to manage the noise caused by the motor. This will need to be added to the design and the analysis done to show that it brings the noise under control.

**Comment by Hawk652** [comment]
the 12V/5V converter is what will manage the noise caused by the motor

**Review by JesseTNRoberts — APPROVED** [review]
Very good

**Comment by JesseTNRoberts** [comment]
I don't have permissions to merge, so please merge this.

**Pull request merged**
